# Generated by Django 4.2.5 on 2025-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='events',
            field=models.ManyToManyField(related_name='cities', to='core.event'),
        ),
    ]
