# Generated by Django 5.0.6 on 2024-11-04 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='guidelines',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='city',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='city',
            name='venue',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
