# Generated by Django 4.2.5 on 2025-09-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_city_city_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(null=True, upload_to='image_uploads/city_pic/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image representing this event', null=True, upload_to='image_uploads/event_pic/'),
        ),
    ]
