# Generated by Django 4.2.5 on 2024-11-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_guidelines_city_time_city_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='ropar.png', upload_to='image_uploads/city_pic/'),
        ),
    ]
