# Generated by Django 4.2.5 on 2025-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_city_image_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='collab',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
