# Generated by Django 4.2.5 on 2025-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFARegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('college_id_card_link', models.URLField()),
                ('college_name', models.CharField(max_length=200)),
                ('college_designation', models.CharField(max_length=100)),
                ('fest_name', models.CharField(max_length=200)),
                ('fest_address', models.TextField()),
                ('fest_dates', models.CharField(max_length=100)),
                ('number_of_days', models.CharField(max_length=50)),
                ('expected_footfall', models.CharField(max_length=100)),
                ('social_links', models.TextField()),
                ('accommodation_required', models.BooleanField(default=False)),
                ('event_preferences', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
