# Generated by Django 5.2.4 on 2025-08-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='is_disabled',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_disabled',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='head',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('P', 'Prefer not to say')], max_length=1),
        ),
        migrations.AlterField(
            model_name='head',
            name='year_of_passing',
            field=models.IntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='year_of_passing',
            field=models.IntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')]),
        ),
    ]
