# Generated by Django 5.2.4 on 2025-08-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_deadline_event_event_date'),
        ('core', '0005_head_is_disabled_teammember_is_disabled_and_more'),
    ]

    operations = [
    ]
