# Generated by Django 5.2.4 on 2025-08-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250814_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
