# Generated by Django 5.2.5 on 2025-08-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cfaregistration'),
        ('core', '0007_city_state'),
    ]

    operations = [
    ]
