# Generated by Django 4.2.5 on 2025-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_0005_cfaregistration_0007_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Team', 'Team')], default='solo', max_length=10),
        ),
    ]
