# Generated by Django 5.1.11 on 2025-09-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], default='solo', max_length=10),
        ),
    ]
