# Generated by Django 5.1.11 on 2025-09-06 18:54

from django.db import migrations


def update_event_types(apps, schema_editor):
    """Update existing 'Team' values to 'team' to match new choices"""
    Event = apps.get_model('core', 'Event')
    Event.objects.filter(event_type='Team').update(event_type='team')


def reverse_update_event_types(apps, schema_editor):
    """Reverse: Update 'team' values back to 'Team'"""
    Event = apps.get_model('core', 'Event')
    Event.objects.filter(event_type='team').update(event_type='Team')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_event_type'),
    ]

    operations = [
        migrations.RunPython(update_event_types, reverse_update_event_types),
    ]
