# Generated by Django 4.2.5 on 2025-09-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250907_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='ropar.png', help_text='Upload an image representing this event', null=True, upload_to='image_uploads/event_pic/'),
        ),
    ]
