# Generated by Django 4.2.5 on 2025-09-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
