# Generated by Django 4.2.5 on 2025-09-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_city_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='events',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.city'),
        ),
    ]
